extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../../bril/benchmarks/core/*.bril'

[runs.baseline]
pipeline = ["bril2json", "brili -p {args}"]

[runs.localopt]
pipeline = ["bril2json", "./local_opt", "brili -p {args}"]
